import = ["~/.config/alacritty/themes/themes/campbell.toml"]

live_config_reload = true

[cursor]
style = { shape = "Block", blinking = "Never" }

[window]
padding.x = 0
padding.y = 0
decorations = "Full"
decorations_theme_variant = "Dark"

[font]
normal.family = "SauceCodePro Nerd Font Mono"
bold.family = "SauceCodePro Nerd Font Mono"
italic.family = "SauceCodePro Nerd Font Mono"
bold_italic.family = "SauceCodePro Nerd Font Mono"
size = 9.0

[shell]
program = "/run/current-system/sw/bin/zsh"
args = ["-l"]
