# Hyprdock configuration converted from kanshi config
# Note: Hyprdock handles automatic docking/undocking but doesn't support 
# complex multi-monitor positioning like kanshi profiles

# Default behavior when external monitor is detected
default_external_mode = "extend"

# Custom CSS styling (optional)
css_string = ""

# Commands configuration
[init_command]
base = ""
args = []

[open_bar_command]
base = "ironbar"  # or your preferred bar (waybar, eww, etc.)
args = []

[close_bar_command]
base = "killall"
args = ["ironbar"]  # adjust to match your bar

[reload_bar_command]
base = "ironbar"
args = []

[suspend_command]
base = "systemctl"
args = ["suspend"]

[lock_command]
base = "hyprlock"  # or your preferred lock screen
args = []

[utility_command]
base = "playerctl"
args = ["--all-players", "-a", "pause"]

[get_monitors_command]
base = "hyprctl"
args = ["monitors"]

# Internal monitor (eDP-1) commands
[enable_internal_monitor_command]
base = "hyprctl"
args = ["keyword", "monitor", "eDP-1,2880x1920@120,0x0,2"]

[disable_internal_monitor_command]
base = "hyprctl"
args = ["keyword", "monitor", "eDP-1,disabled"]

# External monitor commands - hyprdock will use the first connected external monitor
[enable_external_monitor_command]
base = "hyprctl"
args = ["keyword", "monitor", ",preferred,auto,1"]

[disable_external_monitor_command]
base = "hyprctl"
args = ["keyword", "monitor", ",disabled"]

# Extend mode positioning
[extend_command]
base = "hyprctl"
args = ["keyword", "monitor", ",preferred,1440x0,1"]

# Mirror mode
[mirror_command]
base = "hyprctl"
args = ["keyword", "monitor", ",2880x1920@60,0x0,1"]

[wallpaper_command]
base = "hyprctl"
args = ["dispatch", "exec", "hyprpaper"]
