#!/bin/bash

notify-send -i display "Display Profile" "$AUTORANDR_CURRENT_PROFILE"
feh --bg-fill /home/$USER/Pictures/Wallpapers/dark_stream.jpg --bg-fill /home/$USER/Pictures/Wallpapers/dark_stream.jpg
xinput set-prop "pointer:PIXA3854:00 093A:0274 Touchpad" "libinput Tapping Enabled" 0
xinput set-prop "pointer:PIXA3854:00 093A:0274 Touchpad" "libinput Scrolling Pixel Distance" 50
xsetroot -cursor_name left_ptr
$HOME/.local/bin/scripts/ghostty-config-updater.sh 22
$HOME/.local/bin/scripts/i3-config-updater.sh 20
i3-msg reload
