return {
  -- {
  --   "saghen/blink.cmp",
  --   dependencies = "L3MON4D3/LuaSnip",
  --   version = "1.*",
  --   opts = {
  --     experimental = {
  --       signatureHelp = {
  --         enabled = false,
  --       },
  --     },
  --
  --     sources = {
  --       default = { 'lsp', 'path', 'snippets', 'buffer' },
  --     },
  --
  --     keymap = { preset = "default" },
  --     ghost_text = { enabled = false },
  --
  --     appearance = {
  --       use_nvim_cmp_as_default = true,
  --       nerd_font_variant = "mono"
  --     },
  --     completion = {
  --       documentation = {
  --         auto_show = true,
  --         window = {
  --           border = "single",
  --         },
  --       },
  --     },
  --
  --     signature = { enabled = true }
  --   },
  --   opts_extend = { "sources.default" }
  -- },
}
